version: "3"
services:
  postgres:
    image: postgres:10.5
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sh:/docker-entrypoint-initdb.d/create_tables.sh