#!/bin/bash
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-22 02:07", "category": "hardware","floor" : "4", "author" : "kmthunzi", "issue":"Python3 and Keyboard","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-21 02:07", "category": "software","floor" : "4", "author" : "ndumasi", "issue":"Bashrc","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-21 02:07", "category": "hardware","floor" : "6", "author" : "kingV", "issue":"Keyboard","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-20 02:07", "category": "lms",     "floor" : "5", "author" : "Vines", "issue":"Youtube crashed","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-26 02:07", "category": "software","floor" : "5", "author" : "Youtube", "issue":"Vines is hassling me","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-25 02:07", "category": "hardware","floor" : "6", "author" : "APex", "issue":"Server not Found","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-26 02:07", "category": "hardware","floor" : "6", "author" : "Javalin4", "issue":"Need to upgrade to Javalin5","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-24 02:07", "category": "software","floor" : "4", "author" : "Javalin5", "issue":"Not compatible with flutter","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-26 02:07", "category": "software","floor" : "0", "author" : "Flutter", "issue":"New and fresh package","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-12 02:07", "category": "lms",     "floor" : "0", "author" : "zakirah", "issue":"Need automation done on all floors, and Durban campus is hungry for Network resolutions and CPT has Ruan....","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-10 02:07", "category": "hardware","floor" : "6", "author" : "sibonelo", "issue":"Broken Keyboard","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-10 02:07", "category": "hardware","floor" : "6", "author" : "sibonelo", "issue":"Need a new Mouse","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"date":"2021-11-10 02:07", "category": "hardware","floor" : "6", "author" : "sibonelo", "issue":"Server not found on Website","campus":"JHB"}'
