#!/bin/bash
curl --request POST "http://$1:4444/tickets" -d '{"author":"kmthunzi","issue":"Python3 and Keyboard","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"ndumasi","issue":"Bashrc","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"kingV","issue":"Keyboard","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"Vines","issue":"Youtube crashed","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"Youtube","issue":"Vines is hassling me","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"APex","issue":"Server not Found","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"Javalin4","issue":"Need to upgrade to Javalin5","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"Javalin5","issue":"Not compatible with flutter","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"Flutter","issue":"New and fresh package","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"zakirah","issue":"Need automation done on all floors, and DUrban campus is hungry for Network resolutions and CPT has Ruan....","campus":"JHB"}'
curl --request POST "http://$1:4444/tickets" -d '{"author":"sibonelo","issue":"Lunch","campus":"JHB"}'
